import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'main.dart';

class AuthScreen extends StatefulWidget {
  final String selectedLanguage;
  const AuthScreen({super.key, this.selectedLanguage = 'en'});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _loginIdentifierController = TextEditingController();
  final _passwordController = TextEditingController();

  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _emailController = TextEditingController();
  final _primaryPhoneController = TextEditingController();
  final _secondaryPhoneController = TextEditingController();
  final _cityController = TextEditingController();
  final _bioController = TextEditingController();
  final _hobbiesController = TextEditingController();
  final _designationController = TextEditingController();
  final _companyOrGovtController = TextEditingController();

  final _whatsappLinkController = TextEditingController();
  final _instagramLinkController = TextEditingController();
  final _facebookLinkController = TextEditingController();
  final _twitterLinkController = TextEditingController();

  DateTime? _selectedBirthDate;
  String _selectedEducation = "primary";
  String _selectedProfessionType = "business";
  String _selectedProfile = "Personal";

  bool _isLogin = false;
  bool _isLoading = false;

  static const Map<String, Map<String, String>> _dict = {
    'en': {
      'app_title_login': 'Star India - Login',
      'app_title_signup': 'Star India - Create Account',
      'header_login': 'Log in to your account',
      'header_signup': 'Create your profile on Star India',
      'sec_personal': 'Personal Details',
      'first_name': 'First Name *',
      'last_name': 'Last Name',
      'pick_birthdate': 'Select Birth Date',
      'birthdate_is': 'Birth Date:',
      'city': 'City / Town',
      'bio': 'Bio / Short description about you',
      'hobbies': 'Hobbies / Interests',
      'sec_work': 'Education & Profession',
      'edu_label': 'Education Level',
      'edu_primary': 'Primary Education',
      'edu_secondary': 'Secondary Education',
      'edu_higher_sec': 'Higher Secondary Education',
      'edu_college': 'College',
      'edu_higher_college': 'Post Graduate / Higher College',
      'edu_degree': 'Degree / Professional',
      'prof_label': 'Profession Type',
      'prof_business': 'Business / Self-Employed',
      'prof_private': 'Private Job',
      'prof_govt': 'Government Job',
      'prof_freelance': 'Professional / Freelancer',
      'prof_student': 'Student',
      'company_name': 'Company / Department / Business Name',
      'designation': 'Designation / Role',
      'sec_contact': 'Contact & Security',
      'phone_label': '10-Digit Mobile Number *',
      'sec_phone_label': 'Secondary Mobile Number (Optional)',
      'email_label': 'Email Address',
      'pwd_label': 'Password (At least 6 characters) *',
      'login_id_label': 'Email or 10-Digit Mobile Number',
      'login_pwd_label': 'Password',
      'sec_social': 'Social Media Profiles',
      'whatsapp': 'WhatsApp Link / Number',
      'instagram': 'Instagram Profile / Username',
      'facebook': 'Facebook Profile Link',
      'twitter': 'Twitter (X) Profile Link',
      'btn_login': 'Log In',
      'btn_signup': 'Create Account & Get Started',
      'switch_to_signup': 'Need a new account? Sign Up',
      'switch_to_login': 'Already have an account? Log In',
      'err_pwd_len': 'Password must be at least 6 characters.',
      'err_empty_login': 'Please enter Email or Mobile Number.',
      'err_empty_name': 'Please enter First Name and Mobile or Email.',
      'err_phone_invalid': 'Please enter a valid 10-digit mobile number.',
    },
    'gu': {
      'app_title_login': 'Star India - લોગિન',
      'app_title_signup': 'Star India - એકાઉન્ટ બનાવો',
      'header_login': 'તમારા એકાઉન્ટમાં લોગિન કરો',
      'header_signup': 'Star India માં નવી પ્રોફાઇલ બનાવો',
      'sec_personal': 'વ્યક્તિગત વિગતો',
      'first_name': 'ફર્સ્ટ નેમ *',
      'last_name': 'લાસ્ટ નેમ',
      'pick_birthdate': 'જન્મ તારીખ પસંદ કરો',
      'birthdate_is': 'બર્થ ડેટ:',
      'city': 'શહેર / ગામ',
      'bio': 'બાયો / તમારા વિશે ટૂંકમાં',
      'hobbies': 'તમારા શોખ / શું પસંદ છે તે',
      'sec_work': 'શિક્ષણ અને વ્યવસાય',
      'edu_label': 'અભ્યાસ / શિક્ષણ લેવલ',
      'edu_primary': 'પ્રાથમિક શિક્ષણ',
      'edu_secondary': 'માધ્યમિક શિક્ષણ',
      'edu_higher_sec': 'ઉચ્ચતર માધ્યમિક શિક્ષણ',
      'edu_college': 'કોલેજ',
      'edu_higher_college': 'ઉચ્ચતર કોલેજ',
      'edu_degree': 'ડિગ્રી / પ્રોફેશનલ',
      'prof_label': 'વ્યવસાયનો પ્રકાર',
      'prof_business': 'ધંધો / બિઝનેસ',
      'prof_private': 'ખાનગી નોકરી',
      'prof_govt': 'સરકારી નોકરી',
      'prof_freelance': 'પ્રોફેશનલ / ફ્રીલાન્સર',
      'prof_student': 'વિદ્યાર્થી',
      'company_name': 'કંપનીનું નામ / સરકારી ખાતું / વ્યવસાયનું નામ',
      'designation': 'ક્યાં સ્થાને / પદ પર છો (Designation)',
      'sec_contact': 'સંપર્ક અને સુરક્ષા',
      'phone_label': '૧૦ આંકડાનો મોબાઈલ નંબર *',
      'sec_phone_label': 'બીજો મોબાઈલ નંબર (ઓપ્શનલ)',
      'email_label': 'ઈમેલ એડ્રેસ',
      'pwd_label': 'પાસવર્ડ બનાવો (ઓછામાં ઓછા 6 આંકડા) *',
      'login_id_label': 'ઈમેલ અથવા 10 આંકડાનો મોબાઈલ નંબર',
      'login_pwd_label': 'પાસવર્ડ',
      'sec_social': 'સોશિયલ મીડિયા લિંક્સ',
      'whatsapp': 'WhatsApp લિંક / નંબર',
      'instagram': 'Instagram લિંક / યુઝરનેમ',
      'facebook': 'Facebook પ્રોફાઇલ લિંક',
      'twitter': 'Twitter (X) પ્રોફાઇલ લિંક',
      'btn_login': 'લોગિન કરો',
      'btn_signup': 'એકાઉન્ટ બનાવો અને શરૂ કરો',
      'switch_to_signup': 'નવું એકાઉન્ટ બનાવવું છે? એકાઉન્ટ બનાવો',
      'switch_to_login': 'પહેલેથી એકાઉન્ટ છે? લોગિન કરો',
      'err_pwd_len': 'પાસવર્ડ ઓછામાં ઓછો 6 આંકડાનો હોવો જોઈએ.',
      'err_empty_login': 'કૃપા કરીને ઈમેલ અથવા મોબાઈલ નંબર દાખલ કરો.',
      'err_empty_name': 'કૃપા કરીને નામ અને ઈમેલ અથવા 10 આંકડાનો મોબાઈલ નંબર ભરો.',
      'err_phone_invalid': 'કૃપા કરીને માન્ય 10 આંકડાનો મોબાઈલ નંબર દાખલ કરો.',
    },
    'hi': {
      'app_title_login': 'Star India - लॉगिन',
      'app_title_signup': 'Star India - खाता बनाएं',
      'header_login': 'अपने खाते में लॉगिन करें',
      'header_signup': 'Star India में नई प्रोफ़ाइल बनाएं',
      'sec_personal': 'व्यक्तिगत विवरण',
      'first_name': 'पहला नाम *',
      'last_name': 'अंतिम नाम',
      'pick_birthdate': 'जन्म तिथि चुनें',
      'birthdate_is': 'जन्म तिथि:',
      'city': 'शहर / गाँव',
      'bio': 'बायो / अपने बारे में संक्षिप्त विवरण',
      'hobbies': 'शौक / रुचियां',
      'sec_work': 'शिक्षा और व्यवसाय',
      'edu_label': 'शिक्षा का स्तर',
      'edu_primary': 'प्राथमिक शिक्षा',
      'edu_secondary': 'माध्यमिक शिक्षा',
      'edu_higher_sec': 'उच्चतर माध्यमिक शिक्षा',
      'edu_college': 'कॉलेज',
      'edu_higher_college': 'स्नातकोत्तर / उच्च कॉलेज',
      'edu_degree': 'डिग्री / पेशेवर',
      'prof_label': 'व्यवसाय का प्रकार',
      'prof_business': 'व्यापार / व्यवसाय',
      'prof_private': 'निजी नौकरी',
      'prof_govt': 'सरकारी नौकरी',
      'prof_freelance': 'पेशेवर / फ्रीलांसर',
      'prof_student': 'छात्र',
      'company_name': 'कंपनी / विभाग / व्यवसाय का नाम',
      'designation': 'पद / भूमिका (Designation)',
      'sec_contact': 'संपर्क और सुरक्षा',
      'phone_label': '10 अंकों का मोबाइल नंबर *',
      'sec_phone_label': 'दूसरा मोबाइल नंबर (वैकल्पिक)',
      'email_label': 'ईमेल पता',
      'pwd_label': 'पासवर्ड बनाएं (कम से कम 6 अक्षर) *',
      'login_id_label': 'ईमेल या 10 अंकों का मोबाइल नंबर',
      'login_pwd_label': 'पासवर्ड',
      'sec_social': 'सोशल मीडिया लिंक',
      'whatsapp': 'WhatsApp लिंक / नंबर',
      'instagram': 'Instagram लिंक / यूजरनेम',
      'facebook': 'Facebook प्रोफाइल लिंक',
      'twitter': 'Twitter (X) प्रोफाइल लिंक',
      'btn_login': 'लॉगिन करें',
      'btn_signup': 'खाता बनाएं और शुरू करें',
      'switch_to_signup': 'नया खाता बनाना है? साइन अप करें',
      'switch_to_login': 'पहले से खाता है? लॉगिन करें',
      'err_pwd_len': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'err_empty_login': 'कृपया ईमेल या मोबाइल नंबर दर्ज करें।',
      'err_empty_name': 'कृपया नाम और ईमेल या 10 अंकों का मोबाइल नंबर दर्ज करें।',
      'err_phone_invalid': 'कृपया मान्य 10 अंकों का मोबाइल नंबर दर्ज करें।',
    },
    'mr': {
      'app_title_login': 'Star India - लॉगिन',
      'app_title_signup': 'Star India - खाते तयार करा',
      'header_login': 'आपल्या खात्यात लॉगिन करा',
      'header_signup': 'Star India वर नवीन प्रोफाईल तयार करा',
      'sec_personal': 'वैयक्तिक माहिती',
      'first_name': 'पहिले नाव *',
      'last_name': 'आडनाव',
      'pick_birthdate': 'जन्मतारीख निवडा',
      'birthdate_is': 'जन्मतारीख:',
      'city': 'शहर / गाव',
      'bio': 'बायो / स्वतःबद्दल थोडक्यात',
      'hobbies': 'छंद / आवडी',
      'sec_work': 'शिक्षण आणि व्यवसाय',
      'edu_label': 'शिक्षणाचा स्तर',
      'edu_primary': 'प्राथमिक शिक्षण',
      'edu_secondary': 'माध्यमिक शिक्षण',
      'edu_higher_sec': 'उच्च माध्यमिक शिक्षण',
      'edu_college': 'कॉलेज',
      'edu_higher_college': 'उच्च महाविद्यालय / पदव्युत्तर',
      'edu_degree': 'पदवी / व्यावसायिक',
      'prof_label': 'व्यवसायाचा प्रकार',
      'prof_business': 'व्यवसाय / उद्योग',
      'prof_private': 'खाजगी नोकरी',
      'prof_govt': 'सरकारी नोकरी',
      'prof_freelance': 'व्यावसायिक / फ्रीलान्सर',
      'prof_student': 'विद्यार्थी',
      'company_name': 'कंपनी / विभाग / व्यवसायाचे नाव',
      'designation': 'पद / भूमिका (Designation)',
      'sec_contact': 'संपर्क आणि सुरक्षितता',
      'phone_label': '१० अंकी मोबाईल नंबर *',
      'sec_phone_label': 'दुसरा मोबाईल नंबर (पर्यायी)',
      'email_label': 'ईमेल पत्ता',
      'pwd_label': 'पासवर्ड तयार करा (किमान ६ अक्षरे) *',
      'login_id_label': 'ईमेल किंवा १० अंकी मोबाईल नंबर',
      'login_pwd_label': 'पासवर्ड',
      'sec_social': 'सोशल मीडिया लिंक्स',
      'whatsapp': 'WhatsApp लिंक / नंबर',
      'instagram': 'Instagram प्रोफाईल / युझरनेम',
      'facebook': 'Facebook प्रोफाईल लिंक',
      'twitter': 'Twitter (X) प्रोफाईल लिंक',
      'btn_login': 'लॉगिन करा',
      'btn_signup': 'खाते तयार करा आणि सुरू करा',
      'switch_to_signup': 'नवीन खाते हवे आहे? साइन अप करा',
      'switch_to_login': 'आधीच खाते आहे? लॉगिन करा',
      'err_pwd_len': 'पासवर्ड किमान ६ अक्षरांचा असावा.',
      'err_empty_login': 'कृपया ईमेल किंवा मोबाईल नंबर प्रविष्ट करा.',
      'err_empty_name': 'कृपया नाव आणि ईमेल किंवा मोबाईल नंबर भरा.',
      'err_phone_invalid': 'कृपया वैध १० अंकी मोबाईल नंबर प्रविष्ट करा.',
    },
    'ta': {
      'app_title_login': 'Star India - உள்நுழைவு',
      'app_title_signup': 'Star India - கணக்கு உருவாக்கு',
      'header_login': 'உங்கள் கணக்கில் உள்நுழையவும்',
      'header_signup': 'Star India இல் புதிய சுயவிவரத்தை உருவாக்கவும்',
      'sec_personal': 'தனிப்பட்ட விவரங்கள்',
      'first_name': 'முதல் பெயர் *',
      'last_name': 'கடைசி பெயர்',
      'pick_birthdate': 'பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்',
      'birthdate_is': 'பிறந்த தேதி:',
      'city': 'நகரம் / கிராமம்',
      'bio': 'பயோ / உங்களைப் பற்றி சுருக்கமாக',
      'hobbies': 'விருப்பங்கள் / பொழுதுபோக்குகள்',
      'sec_work': 'கல்வி மற்றும் தொழில்',
      'edu_label': 'கல்வி நிலை',
      'edu_primary': 'தொடக்கக் கல்வி',
      'edu_secondary': 'இடைநிலைக் கல்வி',
      'edu_higher_sec': 'மேல்நிலைக் கல்வி',
      'edu_college': 'கல்லூரி',
      'edu_higher_college': 'முதுகலை / உயர் கல்லூரி',
      'edu_degree': 'பட்டப்படிப்பு / தொழில்முறை',
      'prof_label': 'தொழில் வகை',
      'prof_business': 'வணிகம் / சுயதொழில்',
      'prof_private': 'தனியார் வேலை',
      'prof_govt': 'அரசு வேலை',
      'prof_freelance': 'தொழில்முறை / ஃப்ரீலான்ஸர்',
      'prof_student': 'மாணவர்',
      'company_name': 'நிறுவனம் / துறை / வணிகப் பெயர்',
      'designation': 'பதவி / பங்கு (Designation)',
      'sec_contact': 'தொடர்பு மற்றும் பாதுகாப்பு',
      'phone_label': '10 இலக்க மொபைல் எண் *',
      'sec_phone_label': 'இரண்டாவது மொபைல் எண் (விருப்பத்தேர்வு)',
      'email_label': 'மின்னஞ்சல் முகவரி',
      'pwd_label': 'கடவுச்சொல் (குறைந்தது 6 எழுத்துக்கள்) *',
      'login_id_label': 'மின்னஞ்சல் அல்லது 10 இலக்க மொபைல் எண்',
      'login_pwd_label': 'கடவுச்சொல்',
      'sec_social': 'சமூக ஊடக இணைப்புகள்',
      'whatsapp': 'WhatsApp இணைப்பு / எண்',
      'instagram': 'Instagram சுயவிவரம்',
      'facebook': 'Facebook சுயவிவர இணைப்பு',
      'twitter': 'Twitter (X) சுயவிவர இணைப்பு',
      'btn_login': 'உள்நுழையவும்',
      'btn_signup': 'கணக்கை உருவாக்கி தொடங்கவும்',
      'switch_to_signup': 'புதிய கணக்கு வேண்டுமா? பதிவு செய்க',
      'switch_to_login': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'err_pwd_len': 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களாக இருக்க வேண்டும்.',
      'err_empty_login': 'மின்னஞ்சல் அல்லது மொபைல் எண்ணை உள்ளிடவும்.',
      'err_empty_name': 'பெயர் மற்றும் மொபைல் அல்லது மின்னஞ்சலை உள்ளிடவும்.',
      'err_phone_invalid': 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
    },
    'te': {
      'app_title_login': 'Star India - లాగిన్',
      'app_title_signup': 'Star India - ఖాతాను సృష్టించండి',
      'header_login': 'మీ ఖాతాకు లాగిన్ చేయండి',
      'header_signup': 'Star India లో కొత్త ప్రొఫైల్ సృష్టించండి',
      'sec_personal': 'వ్యక్తిగత వివరాలు',
      'first_name': 'మొదటి పేరు *',
      'last_name': 'చివరి పేరు',
      'pick_birthdate': 'పుట్టిన తేదీని ఎంచుకోండి',
      'birthdate_is': 'పుట్టిన తేదీ:',
      'city': 'నగరం / గ్రామం',
      'bio': 'బయో / మీ గురించి సంక్షిప్తంగా',
      'hobbies': 'అభిరుచులు / ఇష్టాలు',
      'sec_work': 'విద్య మరియు వృత్తి',
      'edu_label': 'విద్యా స్థాయి',
      'edu_primary': 'ప్రాథమిక విద్య',
      'edu_secondary': 'మాధ్యమిక విద్య',
      'edu_higher_sec': 'ఉన్నత మాధ్యమిక విద్య',
      'edu_college': 'కళాశాల',
      'edu_higher_college': 'పోస్ట్ గ్రాడ్యుయేట్ / ఉన్నత కళాశాల',
      'edu_degree': 'డిగ్రీ / ప్రొఫెషనల్',
      'prof_label': 'వృత్తి రకం',
      'prof_business': 'వ్యాపారం / స్వయం ఉపాధి',
      'prof_private': 'ప్రైవేట్ ఉద్యోగం',
      'prof_govt': 'ప్రభుత్వ ఉద్యోగం',
      'prof_freelance': 'ప్రొఫెషనల్ / ఫ్రీలాన్సర్',
      'prof_student': 'విద్యార్థి',
      'company_name': 'కంపెనీ / విభాగం / వ్యాపార పేరు',
      'designation': 'హోదా / పాత్ర (Designation)',
      'sec_contact': 'సంప్రదింపు మరియు భద్రత',
      'phone_label': '10 అంకెల మొబైల్ నంబర్ *',
      'sec_phone_label': 'రెండవ మొబైల్ నంబర్ (ఐచ్ఛికం)',
      'email_label': 'ఈమెయిల్ చిరునామా',
      'pwd_label': 'పాస్‌వర్డ్ (కనీసం 6 అక్షరాలు) *',
      'login_id_label': 'ఈమెయిల్ లేదా 10 అంకెల మొబైల్ నంబర్',
      'login_pwd_label': 'పాస్‌వర్డ్',
      'sec_social': 'సోషల్ మీడియా లింకులు',
      'whatsapp': 'WhatsApp లింక్ / నంబర్',
      'instagram': 'Instagram ప్రొఫైల్',
      'facebook': 'Facebook ప్రొఫైల్ లింక్',
      'twitter': 'Twitter (X) ప్రొఫైల్ లింక్',
      'btn_login': 'లాగిన్ చేయండి',
      'btn_signup': 'ఖాతాను సృష్టించి ప్రారంభించండి',
      'switch_to_signup': 'కొత్త ఖాతా కావాలా? సైన్ అప్ చేయండి',
      'switch_to_login': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి',
      'err_pwd_len': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.',
      'err_empty_login': 'దయచేసి ఈమెయిల్ లేదా మొబైల్ నంబర్ నమోదు చేయండి.',
      'err_empty_name': 'దయచేసి పేరు మరియు మొబైల్ లేదా ఈమెయిల్ నమోదు చేయండి.',
      'err_phone_invalid': 'దయచేసి సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.',
    },
    'bn': {
      'app_title_login': 'Star India - লগইন',
      'app_title_signup': 'Star India - অ্যাকাউন্ট তৈরি করুন',
      'header_login': 'আপনার অ্যাকাউন্টে লগইন করুন',
      'header_signup': 'Star India-তে নতুন প্রোফাইল তৈরি করুন',
      'sec_personal': 'ব্যক্তিগত বিবরণ',
      'first_name': 'প্রথম নাম *',
      'last_name': 'শেষ নাম',
      'pick_birthdate': 'জন্মতারিখ নির্বাচন করুন',
      'birthdate_is': 'জন্মতারিখ:',
      'city': 'শহর / গ্রাম',
      'bio': 'বায়ো / নিজের সম্পর্কে সংক্ষেপে',
      'hobbies': 'শখ / পছন্দ',
      'sec_work': 'শিক্ষা এবং পেশা',
      'edu_label': 'শিক্ষাগত যোগ্যতা',
      'edu_primary': 'প্রাথমিক শিক্ষা',
      'edu_secondary': 'মাধ্যমিক শিক্ষা',
      'edu_higher_sec': 'উচ্চ মাধ্যমিক শিক্ষা',
      'edu_college': 'কলেজ',
      'edu_higher_college': 'স্নাতকোত্তর / উচ্চ কলেজ',
      'edu_degree': 'ডিগ্রি / পেশাদার',
      'prof_label': 'পেশার ধরন',
      'prof_business': 'ব্যবসা / স্বনিযুক্ত',
      'prof_private': 'বেসরকারি চাকরি',
      'prof_govt': 'সরকারি চাকরি',
      'prof_freelance': 'পেশাদার / ফ্রিল্যান্সার',
      'prof_student': 'ছাত্র / ছাত্রী',
      'company_name': 'কোম্পানি / বিভাগ / ব্যবসার নাম',
      'designation': 'পদবী / ভূমিকা (Designation)',
      'sec_contact': 'যোগাযোগ এবং নিরাপত্তা',
      'phone_label': '১০ সংখ্যার মোবাইল নম্বর *',
      'sec_phone_label': 'দ্বিতীয় মোবাইল নম্বর (ঐচ্ছিক)',
      'email_label': 'ইমেল ঠিকানা',
      'pwd_label': 'পাসওয়ার্ড (কমপক্ষে ৬ অক্ষর) *',
      'login_id_label': 'ইমেল বা ১০ সংখ্যার মোবাইল নম্বর',
      'login_pwd_label': 'পাসওয়ার্ড',
      'sec_social': 'সোশ্যাল মিডিয়া লিঙ্ক',
      'whatsapp': 'WhatsApp লিঙ্ক / নম্বর',
      'instagram': 'Instagram প্রোফাইল',
      'facebook': 'Facebook প্রোফাইল লিঙ্ক',
      'twitter': 'Twitter (X) প্রোফাইল লিঙ্ক',
      'btn_login': 'লগইন করুন',
      'btn_signup': 'অ্যাকাউন্ট তৈরি করে শুরু করুন',
      'switch_to_signup': 'নতুন অ্যাকাউন্ট প্রয়োজন? সাইন আপ করুন',
      'switch_to_login': 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',
      'err_pwd_len': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
      'err_empty_login': 'অনুগ্রহ করে ইমেল বা মোবাইল নম্বর লিখুন।',
      'err_empty_name': 'অনুগ্রহ করে নাম এবং মোবাইল বা ইমেল লিখুন।',
      'err_phone_invalid': 'অনুগ্রহ করে একটি সঠিক ১০ সংখ্যার মোবাইল নম্বর লিখুন।',
    },
    'kn': {
      'app_title_login': 'Star India - ಲಾಗಿನ್',
      'app_title_signup': 'Star India - ಖಾತೆ ರಚಿಸಿ',
      'header_login': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
      'header_signup': 'Star India ನಲ್ಲಿ ಹೊಸ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
      'sec_personal': 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
      'first_name': 'ಮೊದಲ ಹೆಸರು *',
      'last_name': 'ಕೊನೆಯ ಹೆಸರು',
      'pick_birthdate': 'ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'birthdate_is': 'ಹುಟ್ಟಿದ ದಿನಾಂಕ:',
      'city': 'ನಗರ / ಊರು',
      'bio': 'ಬಯೋ / ನಿಮ್ಮ ಬಗ್ಗೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ',
      'hobbies': 'ಹವ್ಯಾಸಗಳು / ಆಸಕ್ತಿಗಳು',
      'sec_work': 'ಶಿಕ್ಷಣ ಮತ್ತು ಉದ್ಯೋಗ',
      'edu_label': 'ಶಿಕ್ಷಣದ ಮಟ್ಟ',
      'edu_primary': 'ಪ್ರಾಥಮಿಕ ಶಿಕ್ಷಣ',
      'edu_secondary': 'ಪ್ರೌಢ ಶಿಕ್ಷಣ',
      'edu_higher_sec': 'ಪದವಿ ಪೂರ್ವ ಶಿಕ್ಷಣ',
      'edu_college': 'ಕಾಲೇಜು',
      'edu_higher_college': 'ಸ್ನಾತಕೋತ್ತರ / ಉನ್ನತ ಕಾಲೇಜು',
      'edu_degree': 'ಪದವಿ / ವೃತ್ತಿಪರ',
      'prof_label': 'ಉದ್ಯೋಗದ ಪ್ರಕಾರ',
      'prof_business': 'ವ್ಯಾಪಾರ / ಸ್ವಯಂ ಉದ್ಯೋಗ',
      'prof_private': 'ಖಾಸಗಿ ಉದ್ಯೋಗ',
      'prof_govt': 'ಸರ್ಕಾರಿ ಉದ್ಯೋಗ',
      'prof_freelance': 'ವೃತ್ತಿಪರ / ಫ್ರೀಲಾನ್ಸರ್',
      'prof_student': 'ವಿದ್ಯಾರ್ಥಿ',
      'company_name': 'ಕಂಪನಿ / ಇಲಾಖೆ / ವ್ಯವಹಾರದ ಹೆಸರು',
      'designation': 'ಹುದ್ದೆ / ಪಾತ್ರ (Designation)',
      'sec_contact': 'ಸಂಪರ್ಕ ಮತ್ತು ಭದ್ರತೆ',
      'phone_label': '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *',
      'sec_phone_label': 'ಎರಡನೇ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ (ಐಚ್ಛಿಕ)',
      'email_label': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'pwd_label': 'ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು) *',
      'login_id_label': 'ಇಮೇಲ್ ಅಥವಾ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'login_pwd_label': 'ಪಾಸ್‌ವರ್ಡ್',
      'sec_social': 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಲಿಂಕ್‌ಗಳು',
      'whatsapp': 'WhatsApp ಲಿಂಕ್ / ಸಂಖ್ಯೆ',
      'instagram': 'Instagram ಪ್ರೊಫೈಲ್',
      'facebook': 'Facebook ಪ್ರೊಫೈಲ್ ಲಿಂಕ್',
      'twitter': 'Twitter (X) ಪ್ರೊಫೈಲ್ ಲಿಂಕ್',
      'btn_login': 'ಲಾಗಿನ್ ಮಾಡಿ',
      'btn_signup': 'ಖಾತೆ ರಚಿಸಿ ಪ್ರಾರಂಭಿಸಿ',
      'switch_to_signup': 'ಹೊಸ ಖಾತೆ ಬೇಕೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'switch_to_login': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
      'err_pwd_len': 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
      'err_empty_login': 'ದಯವಿಟ್ಟು ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
      'err_empty_name': 'ದಯವಿಟ್ಟು ಹೆಸರು ಮತ್ತು ಮೊಬೈಲ್ ಅಥವಾ ಇಮೇಲ್ ನಮೂದಿಸಿ.',
      'err_phone_invalid': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ
